name: Deploy Project

on: 
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    # container:
    #   image: node:20
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Connect to Tailscale
        # uses: tailscale/github-action@v2
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      # - name: Do the deploy thing
      #   run: |
      #       ssh -o "StrictHostKeyChecking no" ironicbadger@ktz-cloud "
      #         cd ${{ secrets.VPS_PROJET_PATH }}
      #         git pull
      #         docker-compose run pms-wiki build
      #       "


      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 100.69.0.69 # Tailscale IP server
          username: fufufafa
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/myapp
            git pull origin main




      # - uses: actions/checkout@v3
      #   with:
      #     node-version: 20
      # - run: npm cli
      # - run: npm run build
      # - name: Get SSH Key and Set permission
      #   run: 
      #     mkdir -p ~/.ssh
      #     echo "${{ secrect.SSH_PRIVATE.KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      # - name: Deploy using SCP
      #   run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./dist/* ${{ secrect.SSH_USER }}@${{ secrect.SSH_HOST }}:~/node-app
      # - name: Restart Server
      #   run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrect.SSH_USER }}@${{ secrect.SSH_HOST }}"cd ~/node-app && npm install && pm2 restart"